# Generated by Django 2.1.2 on 2018-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('codigo_livro', models.CharField(max_length=100)),
                ('codigo_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('escola', models.CharField(max_length=30)),
            ],
        ),
    ]
