# Generated by Django 2.1.2 on 2018-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blibliopy', '0002_auto_20181014_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestar',
            name='validar',
            field=models.BooleanField(default=True),
        ),
    ]
