# Generated by Django 2.1.2 on 2018-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blibliopy', '0003_emprestar_validar'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestar',
            name='turma',
            field=models.CharField(choices=[('p', 'Pré'), ('1a', '1º ano'), ('2a', '2º ano'), ('3a', '3º ano'), ('4a', '4º ano'), ('5a', '5º ano'), ('6a', '6º ano'), ('7a', '7º ano'), ('8a', '8º ano'), ('9a', '9º ano')], default=1994, max_length=3, verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
